version: '3'
services:
  specifdb:
    image: mongo:4.2.2
    ports:
      - "27019:27017"
    volumes:
      - specifdb:/data/db
      - specifdb-config:/data/configdb
      - ./mongodb-init-data:/mongodb_specif_data
      - ./mongodb-init-data/init-mongodb.sh:/docker-entrypoint-initdb.d/init-mongodb.sh
volumes:
  specifdb: {}  
  specifdb-config: {}