version: '3'
services:
  specifdb:
    image: mongo:4.2.2
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - specifdb:/data/db
      - specifdb-config:/data/configdb
      - ./mongodb-init-data:/mongodb_specif_data
      - ./mongodb-init-data/init-mongodb.sh:/docker-entrypoint-initdb.d/init-mongodb.sh
   
  api:    
    build: .
    container_name: specif_backend
    ports:
      - "888:888"
      - "887:887"
      - "555:555"
      - "554:554"


    environment:
      - "dataConnection=mongodb://mongo:27017"
 
    
     
volumes:
  specifdb: {}  
  specifdb-config: {}